/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditEntry {
  'id' : string,
  'oldValue' : [] | [string],
  'resourceId' : string,
  'newValue' : [] | [string],
  'actionType' : string,
  'actorId' : string,
  'resourceType' : string,
  'timestamp' : Timestamp,
  'details' : string,
}
export interface CommissionRecord {
  'id' : bigint,
  'rate' : number,
  'productId' : string,
  'orderId' : bigint,
  'timestamp' : Timestamp,
  'sellerId' : UserId,
  'amount' : number,
}
export interface CommissionSummary {
  'totalCommission' : number,
  'topProducts' : Array<[string, number]>,
  'topSellers' : Array<[UserId, number]>,
  'byPeriod' : Array<[string, number]>,
}
export interface LeaderboardEntry {
  'totalRewardEarned' : number,
  'totalReferrals' : bigint,
  'rank' : bigint,
  'lastReferralDate' : bigint,
  'referrerId' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : number,
  'userId' : UserId,
  'date' : Timestamp,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'qty' : bigint, 'name' : string, 'price' : number }
export type OrderStatus = { 'Delivered' : null } |
  { 'Ongoing' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'Nagad' : null } |
  { 'bKash' : null };
export interface PaymentRecord {
  'id' : bigint,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'sellerEarnings' : number,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'commission' : number,
  'reviewedAt' : [] | [Timestamp],
  'orderId' : bigint,
  'amount' : number,
  'transactionId' : string,
}
export type PaymentStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : string,
  'subcategory' : string,
  'stockStatus' : StockStatus,
  'shopDescription' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'sellerName' : string,
  'updatedAt' : Timestamp,
  'shopName' : string,
  'sellerId' : UserId,
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
  'images' : Array<string>,
}
export interface ReferralRecord {
  'id' : string,
  'status' : ReferralStatus,
  'completedAt' : Timestamp,
  'referrerReward' : bigint,
  'code' : string,
  'refereeId' : string,
  'refereeBonus' : bigint,
  'referrerId' : string,
}
export type ReferralStatus = { 'Invalid' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface SellerDashboardSummary {
  'totalNetEarnings' : number,
  'remainingBalance' : number,
  'totalWithdrawn' : number,
  'periodLabel' : string,
  'totalGrossRevenue' : number,
  'totalCommissionDeducted' : number,
}
export interface SellerEarningsByPeriod {
  'period' : string,
  'grossRevenue' : number,
  'netRevenue' : number,
  'commissionDeducted' : number,
}
export interface SellerProductStat {
  'productId' : string,
  'productName' : string,
  'netRevenue' : number,
  'salesCount' : bigint,
  'totalRevenue' : number,
  'commissionDeducted' : number,
}
export interface SellerWallet {
  'pendingWithdrawal' : number,
  'totalWithdrawn' : number,
  'totalEarnings' : number,
  'sellerId' : UserId,
}
export interface ShopOwnerProfile {
  'userId' : UserId,
  'shopDescription' : string,
  'updatedAt' : Timestamp,
  'shopName' : string,
}
export type StockStatus = string;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'Customer' : null } |
  { 'Seller' : null } |
  { 'Admin' : null };
export interface WithdrawRequest {
  'id' : bigint,
  'status' : WithdrawStatus,
  'method' : PaymentMethod,
  'reviewedAt' : [] | [Timestamp],
  'sellerId' : UserId,
  'accountNumber' : string,
  'amount' : number,
  'requestedAt' : Timestamp,
}
export type WithdrawStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'approvePayment' : ActorMethod<[bigint], boolean>,
  'approveWithdrawal' : ActorMethod<[bigint], boolean>,
  'assignRole' : ActorMethod<
    [UserId, UserRole],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'checkLoginLockout' : ActorMethod<
    [string],
    { 'locked' : boolean, 'remainingSecs' : bigint }
  >,
  'clearLoginAttempts' : ActorMethod<[string], undefined>,
  'createOrder' : ActorMethod<[Array<OrderItem>], Order>,
  'createReferralCode' : ActorMethod<[string], string>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'generateOtp' : ActorMethod<[string, string], string>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'newOrders' : bigint,
      'pendingPayments' : bigint,
      'pendingWithdrawals' : bigint,
    }
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSellerLimits' : ActorMethod<[], Array<[string, number]>>,
  'getAllSellerSuspensions' : ActorMethod<[bigint, bigint], Array<AuditEntry>>,
  'getAuditLog' : ActorMethod<[bigint, bigint], Array<AuditEntry>>,
  'getAuditLogByAction' : ActorMethod<
    [string, bigint, bigint],
    Array<AuditEntry>
  >,
  'getAuditLogByActor' : ActorMethod<
    [string, bigint, bigint],
    Array<AuditEntry>
  >,
  'getAuditLogByDateRange' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    Array<AuditEntry>
  >,
  'getCommissionByMonth' : ActorMethod<[bigint], Array<[string, number]>>,
  'getCommissionByPeriod' : ActorMethod<[string], Array<[string, number]>>,
  'getCommissionSummary' : ActorMethod<[], CommissionSummary>,
  'getFeaturedIds' : ActorMethod<[string], Array<string>>,
  'getFeaturedIdsByCategory' : ActorMethod<[string], Array<string>>,
  'getMyEarningsByPeriod' : ActorMethod<
    [bigint, string],
    Array<SellerEarningsByPeriod>
  >,
  'getMyEarningsSummary' : ActorMethod<[bigint], SellerDashboardSummary>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyPrincipal' : ActorMethod<[], string>,
  'getMyProductStats' : ActorMethod<[bigint], Array<SellerProductStat>>,
  'getMyReferralEarnings' : ActorMethod<[], bigint>,
  'getMyReferrals' : ActorMethod<[], Array<ReferralRecord>>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getMySellerOrders' : ActorMethod<[], Array<Order>>,
  'getPayment' : ActorMethod<[bigint], [] | [PaymentRecord]>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProductsBySeller' : ActorMethod<[UserId], Array<Product>>,
  'getReferralCode' : ActorMethod<[string], [] | [string]>,
  'getReferralLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getSellerWallet' : ActorMethod<[UserId], [] | [SellerWallet]>,
  'getSellerWithdrawalLimit' : ActorMethod<[string], [] | [number]>,
  'getShopOwnerProfile' : ActorMethod<[UserId], [] | [ShopOwnerProfile]>,
  'getSuspensionAuditTrail' : ActorMethod<[string], Array<AuditEntry>>,
  'getTopProducts' : ActorMethod<[bigint], Array<[string, number]>>,
  'getTopSellers' : ActorMethod<[bigint], Array<[UserId, number]>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[UserId], UserRole>,
  'isAdminSetup' : ActorMethod<[], boolean>,
  'listAllPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'listAllWithdrawals' : ActorMethod<[], Array<WithdrawRequest>>,
  'listCommissions' : ActorMethod<[], Array<CommissionRecord>>,
  'listPendingPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'listPendingWithdrawals' : ActorMethod<[], Array<WithdrawRequest>>,
  'myPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'myWallet' : ActorMethod<[], SellerWallet>,
  'myWithdrawals' : ActorMethod<[], Array<WithdrawRequest>>,
  'processReferral' : ActorMethod<[string, string], boolean>,
  'recordLoginFailure' : ActorMethod<[string], bigint>,
  'rejectPayment' : ActorMethod<[bigint], boolean>,
  'rejectWithdrawal' : ActorMethod<[bigint], boolean>,
  'requestAdminRole' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'requestWithdrawal' : ActorMethod<[number, PaymentMethod, string], bigint>,
  'resetAdminLockout' : ActorMethod<[], undefined>,
  'resetAdminPassword' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSellerWithdrawalLimit' : ActorMethod<[string, number], undefined>,
  'setUserProfile' : ActorMethod<[string], undefined>,
  'setupAdminPassword' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitPayment' : ActorMethod<
    [bigint, PaymentMethod, string, number],
    bigint
  >,
  'updateFeaturedIds' : ActorMethod<
    [string, Array<string>, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [bigint, OrderStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateShopOwnerProfile' : ActorMethod<[ShopOwnerProfile], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
  'verifyOtp' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];