/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : number,
  'userId' : UserId,
  'date' : Timestamp,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'qty' : bigint, 'name' : string, 'price' : number }
export type OrderStatus = { 'Delivered' : null } |
  { 'Ongoing' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'Customer' : null } |
  { 'Seller' : null } |
  { 'Admin' : null };
export interface _SERVICE {
  'assignRole' : ActorMethod<
    [UserId, UserRole],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createOrder' : ActorMethod<[Array<OrderItem>], Order>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getFeaturedIds' : ActorMethod<[string], Array<string>>,
  'getFeaturedIdsByCategory' : ActorMethod<[string], Array<string>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyPrincipal' : ActorMethod<[], string>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[UserId], UserRole>,
  'isAdminSetup' : ActorMethod<[], boolean>,
  'requestAdminRole' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'resetAdminPassword' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setUserProfile' : ActorMethod<[string], undefined>,
  'setupAdminPassword' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateFeaturedIds' : ActorMethod<
    [string, Array<string>, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [bigint, OrderStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];