/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'Customer' : IDL.Null,
  'Seller' : IDL.Null,
  'Admin' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Ongoing' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'userId' : UserId,
  'date' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });

export const idlService = IDL.Service({
  'assignRole' : IDL.Func(
      [UserId, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createOrder' : IDL.Func([IDL.Vec(OrderItem)], [Order], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getFeaturedIds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedIdsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserRole' : IDL.Func([UserId], [UserRole], ['query']),
  'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
  'requestAdminRole' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'resetAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setUserProfile' : IDL.Func([IDL.Text], [], []),
  'setupAdminPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateFeaturedIds' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Nat, OrderStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'Customer' : IDL.Null,
    'Seller' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Ongoing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'userId' : UserId,
    'date' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  
  return IDL.Service({
    'assignRole' : IDL.Func(
        [UserId, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createOrder' : IDL.Func([IDL.Vec(OrderItem)], [Order], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getFeaturedIds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedIdsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserRole' : IDL.Func([UserId], [UserRole], ['query']),
    'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
    'requestAdminRole' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'resetAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setUserProfile' : IDL.Func([IDL.Text], [], []),
    'setupAdminPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateFeaturedIds' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, OrderStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };