/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'Customer' : IDL.Null,
  'Seller' : IDL.Null,
  'Admin' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Ongoing' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'userId' : UserId,
  'date' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'oldValue' : IDL.Opt(IDL.Text),
  'resourceId' : IDL.Text,
  'newValue' : IDL.Opt(IDL.Text),
  'actionType' : IDL.Text,
  'actorId' : IDL.Text,
  'resourceType' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
});
export const CommissionSummary = IDL.Record({
  'totalCommission' : IDL.Float64,
  'topProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'topSellers' : IDL.Vec(IDL.Tuple(UserId, IDL.Float64)),
  'byPeriod' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const SellerEarningsByPeriod = IDL.Record({
  'period' : IDL.Text,
  'grossRevenue' : IDL.Float64,
  'netRevenue' : IDL.Float64,
  'commissionDeducted' : IDL.Float64,
});
export const SellerDashboardSummary = IDL.Record({
  'totalNetEarnings' : IDL.Float64,
  'remainingBalance' : IDL.Float64,
  'totalWithdrawn' : IDL.Float64,
  'periodLabel' : IDL.Text,
  'totalGrossRevenue' : IDL.Float64,
  'totalCommissionDeducted' : IDL.Float64,
});
export const SellerProductStat = IDL.Record({
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'netRevenue' : IDL.Float64,
  'salesCount' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'commissionDeducted' : IDL.Float64,
});
export const ReferralStatus = IDL.Variant({
  'Invalid' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ReferralRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : ReferralStatus,
  'completedAt' : Timestamp,
  'referrerReward' : IDL.Nat,
  'code' : IDL.Text,
  'refereeId' : IDL.Text,
  'refereeBonus' : IDL.Nat,
  'referrerId' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'Nagad' : IDL.Null,
  'bKash' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'sellerEarnings' : IDL.Float64,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'commission' : IDL.Float64,
  'reviewedAt' : IDL.Opt(Timestamp),
  'orderId' : IDL.Nat,
  'amount' : IDL.Float64,
  'transactionId' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'totalRewardEarned' : IDL.Float64,
  'totalReferrals' : IDL.Nat,
  'rank' : IDL.Nat,
  'lastReferralDate' : IDL.Int,
  'referrerId' : IDL.Text,
});
export const SellerWallet = IDL.Record({
  'pendingWithdrawal' : IDL.Float64,
  'totalWithdrawn' : IDL.Float64,
  'totalEarnings' : IDL.Float64,
  'sellerId' : UserId,
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const WithdrawStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WithdrawRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawStatus,
  'method' : PaymentMethod,
  'reviewedAt' : IDL.Opt(Timestamp),
  'sellerId' : UserId,
  'accountNumber' : IDL.Text,
  'amount' : IDL.Float64,
  'requestedAt' : Timestamp,
});
export const CommissionRecord = IDL.Record({
  'id' : IDL.Nat,
  'rate' : IDL.Float64,
  'productId' : IDL.Text,
  'orderId' : IDL.Nat,
  'timestamp' : Timestamp,
  'sellerId' : UserId,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'approvePayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignRole' : IDL.Func(
      [UserId, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'checkLoginLockout' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'locked' : IDL.Bool, 'remainingSecs' : IDL.Int })],
      ['query'],
    ),
  'clearLoginAttempts' : IDL.Func([IDL.Text], [], []),
  'createOrder' : IDL.Func([IDL.Vec(OrderItem)], [Order], []),
  'createReferralCode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'newOrders' : IDL.Nat,
          'pendingPayments' : IDL.Nat,
          'pendingWithdrawals' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllSellerLimits' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getAllSellerSuspensions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAuditLog' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAuditLogByAction' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAuditLogByActor' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAuditLogByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getCommissionByMonth' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getCommissionByPeriod' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getCommissionSummary' : IDL.Func([], [CommissionSummary], ['query']),
  'getFeaturedIds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedIdsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getMyEarningsByPeriod' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(SellerEarningsByPeriod)],
      ['query'],
    ),
  'getMyEarningsSummary' : IDL.Func(
      [IDL.Nat],
      [SellerDashboardSummary],
      ['query'],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getMyProductStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SellerProductStat)],
      ['query'],
    ),
  'getMyReferralEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyReferrals' : IDL.Func([], [IDL.Vec(ReferralRecord)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getMySellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentRecord)], ['query']),
  'getReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getReferralLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getSellerWallet' : IDL.Func([UserId], [IDL.Opt(SellerWallet)], ['query']),
  'getSellerWithdrawalLimit' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getSuspensionAuditTrail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getTopProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTopSellers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(UserId, IDL.Float64))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserRole' : IDL.Func([UserId], [UserRole], ['query']),
  'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'listAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawRequest)], ['query']),
  'listCommissions' : IDL.Func([], [IDL.Vec(CommissionRecord)], ['query']),
  'listPendingPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'listPendingWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(WithdrawRequest)],
      ['query'],
    ),
  'myPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'myWallet' : IDL.Func([], [SellerWallet], ['query']),
  'myWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawRequest)], ['query']),
  'processReferral' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'recordLoginFailure' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'rejectPayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'requestAdminRole' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'requestWithdrawal' : IDL.Func(
      [IDL.Float64, PaymentMethod, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'resetAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSellerWithdrawalLimit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'setUserProfile' : IDL.Func([IDL.Text], [], []),
  'setupAdminPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitPayment' : IDL.Func(
      [IDL.Nat, PaymentMethod, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'updateFeaturedIds' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Nat, OrderStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'Customer' : IDL.Null,
    'Seller' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Ongoing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'userId' : UserId,
    'date' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'oldValue' : IDL.Opt(IDL.Text),
    'resourceId' : IDL.Text,
    'newValue' : IDL.Opt(IDL.Text),
    'actionType' : IDL.Text,
    'actorId' : IDL.Text,
    'resourceType' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
  });
  const CommissionSummary = IDL.Record({
    'totalCommission' : IDL.Float64,
    'topProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'topSellers' : IDL.Vec(IDL.Tuple(UserId, IDL.Float64)),
    'byPeriod' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const SellerEarningsByPeriod = IDL.Record({
    'period' : IDL.Text,
    'grossRevenue' : IDL.Float64,
    'netRevenue' : IDL.Float64,
    'commissionDeducted' : IDL.Float64,
  });
  const SellerDashboardSummary = IDL.Record({
    'totalNetEarnings' : IDL.Float64,
    'remainingBalance' : IDL.Float64,
    'totalWithdrawn' : IDL.Float64,
    'periodLabel' : IDL.Text,
    'totalGrossRevenue' : IDL.Float64,
    'totalCommissionDeducted' : IDL.Float64,
  });
  const SellerProductStat = IDL.Record({
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'netRevenue' : IDL.Float64,
    'salesCount' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'commissionDeducted' : IDL.Float64,
  });
  const ReferralStatus = IDL.Variant({
    'Invalid' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ReferralRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : ReferralStatus,
    'completedAt' : Timestamp,
    'referrerReward' : IDL.Nat,
    'code' : IDL.Text,
    'refereeId' : IDL.Text,
    'refereeBonus' : IDL.Nat,
    'referrerId' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'Nagad' : IDL.Null, 'bKash' : IDL.Null });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'sellerEarnings' : IDL.Float64,
    'userId' : UserId,
    'submittedAt' : Timestamp,
    'commission' : IDL.Float64,
    'reviewedAt' : IDL.Opt(Timestamp),
    'orderId' : IDL.Nat,
    'amount' : IDL.Float64,
    'transactionId' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'totalRewardEarned' : IDL.Float64,
    'totalReferrals' : IDL.Nat,
    'rank' : IDL.Nat,
    'lastReferralDate' : IDL.Int,
    'referrerId' : IDL.Text,
  });
  const SellerWallet = IDL.Record({
    'pendingWithdrawal' : IDL.Float64,
    'totalWithdrawn' : IDL.Float64,
    'totalEarnings' : IDL.Float64,
    'sellerId' : UserId,
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const WithdrawStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WithdrawRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawStatus,
    'method' : PaymentMethod,
    'reviewedAt' : IDL.Opt(Timestamp),
    'sellerId' : UserId,
    'accountNumber' : IDL.Text,
    'amount' : IDL.Float64,
    'requestedAt' : Timestamp,
  });
  const CommissionRecord = IDL.Record({
    'id' : IDL.Nat,
    'rate' : IDL.Float64,
    'productId' : IDL.Text,
    'orderId' : IDL.Nat,
    'timestamp' : Timestamp,
    'sellerId' : UserId,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'approvePayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignRole' : IDL.Func(
        [UserId, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'checkLoginLockout' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'locked' : IDL.Bool, 'remainingSecs' : IDL.Int })],
        ['query'],
      ),
    'clearLoginAttempts' : IDL.Func([IDL.Text], [], []),
    'createOrder' : IDL.Func([IDL.Vec(OrderItem)], [Order], []),
    'createReferralCode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'newOrders' : IDL.Nat,
            'pendingPayments' : IDL.Nat,
            'pendingWithdrawals' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllSellerLimits' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getAllSellerSuspensions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAuditLogByAction' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAuditLogByActor' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAuditLogByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getCommissionByMonth' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getCommissionByPeriod' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getCommissionSummary' : IDL.Func([], [CommissionSummary], ['query']),
    'getFeaturedIds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedIdsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getMyEarningsByPeriod' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(SellerEarningsByPeriod)],
        ['query'],
      ),
    'getMyEarningsSummary' : IDL.Func(
        [IDL.Nat],
        [SellerDashboardSummary],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getMyProductStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SellerProductStat)],
        ['query'],
      ),
    'getMyReferralEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyReferrals' : IDL.Func([], [IDL.Vec(ReferralRecord)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getMySellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentRecord)], ['query']),
    'getReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getReferralLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getSellerWallet' : IDL.Func([UserId], [IDL.Opt(SellerWallet)], ['query']),
    'getSellerWithdrawalLimit' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getSuspensionAuditTrail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getTopProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTopSellers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(UserId, IDL.Float64))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserRole' : IDL.Func([UserId], [UserRole], ['query']),
    'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'listAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawRequest)], ['query']),
    'listCommissions' : IDL.Func([], [IDL.Vec(CommissionRecord)], ['query']),
    'listPendingPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'listPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawRequest)],
        ['query'],
      ),
    'myPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'myWallet' : IDL.Func([], [SellerWallet], ['query']),
    'myWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawRequest)], ['query']),
    'processReferral' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'recordLoginFailure' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'rejectPayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'requestAdminRole' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'requestWithdrawal' : IDL.Func(
        [IDL.Float64, PaymentMethod, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'resetAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSellerWithdrawalLimit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'setUserProfile' : IDL.Func([IDL.Text], [], []),
    'setupAdminPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitPayment' : IDL.Func(
        [IDL.Nat, PaymentMethod, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'updateFeaturedIds' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, OrderStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };