/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SellerDashboardSummary {
    totalNetEarnings: number;
    remainingBalance: number;
    totalWithdrawn: number;
    periodLabel: string;
    totalGrossRevenue: number;
    totalCommissionDeducted: number;
}
export type Timestamp = bigint;
export interface SellerWallet {
    pendingWithdrawal: number;
    totalWithdrawn: number;
    totalEarnings: number;
    sellerId: UserId;
}
export interface LeaderboardEntry {
    totalRewardEarned: number;
    totalReferrals: bigint;
    rank: bigint;
    lastReferralDate: bigint;
    referrerId: string;
}
export interface PaymentRecord {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    sellerEarnings: number;
    userId: UserId;
    submittedAt: Timestamp;
    commission: number;
    reviewedAt?: Timestamp;
    orderId: bigint;
    amount: number;
    transactionId: string;
}
export interface OrderItem {
    qty: bigint;
    name: string;
    price: number;
}
export interface AuditEntry {
    id: string;
    oldValue?: string;
    resourceId: string;
    newValue?: string;
    actionType: string;
    actorId: string;
    resourceType: string;
    timestamp: Timestamp;
    details: string;
}
export interface WithdrawRequest {
    id: bigint;
    status: WithdrawStatus;
    method: PaymentMethod;
    reviewedAt?: Timestamp;
    sellerId: UserId;
    accountNumber: string;
    amount: number;
    requestedAt: Timestamp;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    total: number;
    userId: UserId;
    date: Timestamp;
    items: Array<OrderItem>;
}
export type UserId = Principal;
export interface ReferralRecord {
    id: string;
    status: ReferralStatus;
    completedAt: Timestamp;
    referrerReward: bigint;
    code: string;
    refereeId: string;
    refereeBonus: bigint;
    referrerId: string;
}
export interface CommissionRecord {
    id: bigint;
    rate: number;
    productId: string;
    orderId: bigint;
    timestamp: Timestamp;
    sellerId: UserId;
    amount: number;
}
export interface CommissionSummary {
    totalCommission: number;
    topProducts: Array<[string, number]>;
    topSellers: Array<[UserId, number]>;
    byPeriod: Array<[string, number]>;
}
export interface SellerProductStat {
    productId: string;
    productName: string;
    netRevenue: number;
    salesCount: bigint;
    totalRevenue: number;
    commissionDeducted: number;
}
export interface UserProfile {
    displayName: string;
}
export interface SellerEarningsByPeriod {
    period: string;
    grossRevenue: number;
    netRevenue: number;
    commissionDeducted: number;
}
export enum OrderStatus {
    Delivered = "Delivered",
    Ongoing = "Ongoing",
    Pending = "Pending"
}
export enum PaymentMethod {
    Nagad = "Nagad",
    bKash = "bKash"
}
export enum ReferralStatus {
    Invalid = "Invalid",
    Completed = "Completed",
    Pending = "Pending"
}
export enum UserRole {
    Customer = "Customer",
    Seller = "Seller",
    Admin = "Admin"
}
export enum WithdrawStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export interface backendInterface {
    approvePayment(id: bigint): Promise<boolean>;
    approveWithdrawal(id: bigint): Promise<boolean>;
    assignRole(userId: UserId, role: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    checkLoginLockout(userId: string): Promise<{
        locked: boolean;
        remainingSecs: bigint;
    }>;
    clearLoginAttempts(userId: string): Promise<void>;
    createOrder(items: Array<OrderItem>): Promise<Order>;
    createReferralCode(userId: string): Promise<string>;
    generateOtp(userId: string, action: string): Promise<string>;
    getAdminStats(): Promise<{
        newOrders: bigint;
        pendingPayments: bigint;
        pendingWithdrawals: bigint;
    }>;
    getAllOrders(): Promise<Array<Order>>;
    getAllSellerLimits(): Promise<Array<[string, number]>>;
    getAllSellerSuspensions(limit: bigint, offset: bigint): Promise<Array<AuditEntry>>;
    getAuditLog(limit: bigint, offset: bigint): Promise<Array<AuditEntry>>;
    getAuditLogByAction(actionType: string, limit: bigint, offset: bigint): Promise<Array<AuditEntry>>;
    getAuditLogByActor(actorId: string, limit: bigint, offset: bigint): Promise<Array<AuditEntry>>;
    getAuditLogByDateRange(from: bigint, to: bigint, limit: bigint, offset: bigint): Promise<Array<AuditEntry>>;
    getCommissionByMonth(months: bigint): Promise<Array<[string, number]>>;
    getCommissionByPeriod(filter: string): Promise<Array<[string, number]>>;
    getCommissionSummary(): Promise<CommissionSummary>;
    getFeaturedIds(category: string): Promise<Array<string>>;
    getFeaturedIdsByCategory(category: string): Promise<Array<string>>;
    getMyEarningsByPeriod(days: bigint, granularity: string): Promise<Array<SellerEarningsByPeriod>>;
    getMyEarningsSummary(days: bigint): Promise<SellerDashboardSummary>;
    getMyOrders(): Promise<Array<Order>>;
    getMyPrincipal(): Promise<string>;
    getMyProductStats(days: bigint): Promise<Array<SellerProductStat>>;
    getMyReferralEarnings(): Promise<bigint>;
    getMyReferrals(): Promise<Array<ReferralRecord>>;
    getMyRole(): Promise<UserRole>;
    getMySellerOrders(): Promise<Array<Order>>;
    getPayment(id: bigint): Promise<PaymentRecord | null>;
    getReferralCode(userId: string): Promise<string | null>;
    getReferralLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getSellerWallet(sellerId: UserId): Promise<SellerWallet | null>;
    getSellerWithdrawalLimit(sellerId: string): Promise<number | null>;
    getSuspensionAuditTrail(sellerId: string): Promise<Array<AuditEntry>>;
    getTopProducts(limit: bigint): Promise<Array<[string, number]>>;
    getTopSellers(limit: bigint): Promise<Array<[UserId, number]>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    getUserRole(userId: UserId): Promise<UserRole>;
    isAdminSetup(): Promise<boolean>;
    listAllPayments(): Promise<Array<PaymentRecord>>;
    listAllWithdrawals(): Promise<Array<WithdrawRequest>>;
    listCommissions(): Promise<Array<CommissionRecord>>;
    listPendingPayments(): Promise<Array<PaymentRecord>>;
    listPendingWithdrawals(): Promise<Array<WithdrawRequest>>;
    myPayments(): Promise<Array<PaymentRecord>>;
    myWallet(): Promise<SellerWallet>;
    myWithdrawals(): Promise<Array<WithdrawRequest>>;
    processReferral(refereeId: string, referralCode: string): Promise<boolean>;
    recordLoginFailure(userId: string): Promise<bigint>;
    rejectPayment(id: bigint): Promise<boolean>;
    rejectWithdrawal(id: bigint): Promise<boolean>;
    requestAdminRole(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    requestWithdrawal(amount: number, method: PaymentMethod, accountNumber: string): Promise<bigint>;
    resetAdminPassword(oldHash: string, newHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setSellerWithdrawalLimit(sellerId: string, limit: number): Promise<void>;
    setUserProfile(displayName: string): Promise<void>;
    setupAdminPassword(passwordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitPayment(orderId: bigint, method: PaymentMethod, transactionId: string, amount: number): Promise<bigint>;
    updateFeaturedIds(category: string, ids: Array<string>, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyAdminPassword(passwordHash: string): Promise<boolean>;
    verifyOtp(userId: string, action: string, code: string): Promise<boolean>;
}
import type { AuditEntry as _AuditEntry, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PaymentRecord as _PaymentRecord, PaymentStatus as _PaymentStatus, ReferralRecord as _ReferralRecord, ReferralStatus as _ReferralStatus, SellerWallet as _SellerWallet, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, WithdrawRequest as _WithdrawRequest, WithdrawStatus as _WithdrawStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approvePayment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePayment(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignRole(arg0: UserId, arg1: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkLoginLockout(arg0: string): Promise<{
        locked: boolean;
        remainingSecs: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkLoginLockout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkLoginLockout(arg0);
            return result;
        }
    }
    async clearLoginAttempts(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLoginAttempts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLoginAttempts(arg0);
            return result;
        }
    }
    async createOrder(arg0: Array<OrderItem>): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReferralCode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReferralCode(arg0);
            return result;
        }
    }
    async generateOtp(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOtp(arg0, arg1);
            return result;
        }
    }
    async getAdminStats(): Promise<{
        newOrders: bigint;
        pendingPayments: bigint;
        pendingWithdrawals: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSellerLimits(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSellerLimits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSellerLimits();
            return result;
        }
    }
    async getAllSellerSuspensions(arg0: bigint, arg1: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSellerSuspensions(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSellerSuspensions(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(arg0: bigint, arg1: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogByAction(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogByAction(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogByAction(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogByActor(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogByActor(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogByActor(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogByDateRange(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogByDateRange(arg0, arg1, arg2, arg3);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogByDateRange(arg0, arg1, arg2, arg3);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommissionByMonth(arg0: bigint): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommissionByMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommissionByMonth(arg0);
            return result;
        }
    }
    async getCommissionByPeriod(arg0: string): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommissionByPeriod(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommissionByPeriod(arg0);
            return result;
        }
    }
    async getCommissionSummary(): Promise<CommissionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommissionSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommissionSummary();
            return result;
        }
    }
    async getFeaturedIds(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedIds(arg0);
            return result;
        }
    }
    async getFeaturedIdsByCategory(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedIdsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedIdsByCategory(arg0);
            return result;
        }
    }
    async getMyEarningsByPeriod(arg0: bigint, arg1: string): Promise<Array<SellerEarningsByPeriod>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEarningsByPeriod(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEarningsByPeriod(arg0, arg1);
            return result;
        }
    }
    async getMyEarningsSummary(arg0: bigint): Promise<SellerDashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEarningsSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEarningsSummary(arg0);
            return result;
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPrincipal();
            return result;
        }
    }
    async getMyProductStats(arg0: bigint): Promise<Array<SellerProductStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProductStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProductStats(arg0);
            return result;
        }
    }
    async getMyReferralEarnings(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReferralEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReferralEarnings();
            return result;
        }
    }
    async getMyReferrals(): Promise<Array<ReferralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReferrals();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReferrals();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySellerOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySellerOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySellerOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralCode(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCode(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCode(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralLeaderboard();
            return result;
        }
    }
    async getSellerWallet(arg0: UserId): Promise<SellerWallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerWallet(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerWallet(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSellerWithdrawalLimit(arg0: string): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerWithdrawalLimit(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerWithdrawalLimit(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuspensionAuditTrail(arg0: string): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuspensionAuditTrail(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuspensionAuditTrail(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopProducts(arg0: bigint): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopProducts(arg0);
            return result;
        }
    }
    async getTopSellers(arg0: bigint): Promise<Array<[UserId, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopSellers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopSellers(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: UserId): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminSetup(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminSetup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminSetup();
            return result;
        }
    }
    async listAllPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPayments();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPayments();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllWithdrawals(): Promise<Array<WithdrawRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllWithdrawals();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllWithdrawals();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCommissions(): Promise<Array<CommissionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCommissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCommissions();
            return result;
        }
    }
    async listPendingPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingPayments();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingPayments();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingWithdrawals(): Promise<Array<WithdrawRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingWithdrawals();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingWithdrawals();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async myPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.myPayments();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.myPayments();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async myWallet(): Promise<SellerWallet> {
        if (this.processError) {
            try {
                const result = await this.actor.myWallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.myWallet();
            return result;
        }
    }
    async myWithdrawals(): Promise<Array<WithdrawRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.myWithdrawals();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.myWithdrawals();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async processReferral(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.processReferral(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processReferral(arg0, arg1);
            return result;
        }
    }
    async recordLoginFailure(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLoginFailure(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLoginFailure(arg0);
            return result;
        }
    }
    async rejectPayment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPayment(arg0);
            return result;
        }
    }
    async rejectWithdrawal(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async requestAdminRole(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestAdminRole();
                return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestAdminRole();
            return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestWithdrawal(arg0: number, arg1: PaymentMethod, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_PaymentMethod_n37(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_PaymentMethod_n37(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async resetAdminPassword(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminPassword(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminPassword(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setSellerWithdrawalLimit(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSellerWithdrawalLimit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSellerWithdrawalLimit(arg0, arg1);
            return result;
        }
    }
    async setUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(arg0);
            return result;
        }
    }
    async setupAdminPassword(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setupAdminPassword(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupAdminPassword(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitPayment(arg0: bigint, arg1: PaymentMethod, arg2: string, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPayment(arg0, to_candid_PaymentMethod_n37(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPayment(arg0, to_candid_PaymentMethod_n37(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateFeaturedIds(arg0: string, arg1: Array<string>, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeaturedIds(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeaturedIds(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AuditEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEntry): AuditEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ReferralRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferralRecord): ReferralRecord {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ReferralStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferralStatus): ReferralStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawRequest_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawRequest): WithdrawRequest {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawStatus): WithdrawStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : from_candid_PaymentRecord_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SellerWallet]): SellerWallet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    oldValue: [] | [string];
    resourceId: string;
    newValue: [] | [string];
    actionType: string;
    actorId: string;
    resourceType: string;
    timestamp: _Timestamp;
    details: string;
}): {
    id: string;
    oldValue?: string;
    resourceId: string;
    newValue?: string;
    actionType: string;
    actorId: string;
    resourceType: string;
    timestamp: Timestamp;
    details: string;
} {
    return {
        id: value.id,
        oldValue: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.oldValue)),
        resourceId: value.resourceId,
        newValue: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.newValue)),
        actionType: value.actionType,
        actorId: value.actorId,
        resourceType: value.resourceType,
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ReferralStatus;
    completedAt: _Timestamp;
    referrerReward: bigint;
    code: string;
    refereeId: string;
    refereeBonus: bigint;
    referrerId: string;
}): {
    id: string;
    status: ReferralStatus;
    completedAt: Timestamp;
    referrerReward: bigint;
    code: string;
    refereeId: string;
    refereeBonus: bigint;
    referrerId: string;
} {
    return {
        id: value.id,
        status: from_candid_ReferralStatus_n16(_uploadFile, _downloadFile, value.status),
        completedAt: value.completedAt,
        referrerReward: value.referrerReward,
        code: value.code,
        refereeId: value.refereeId,
        refereeBonus: value.refereeBonus,
        referrerId: value.referrerId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    method: _PaymentMethod;
    sellerEarnings: number;
    userId: _UserId;
    submittedAt: _Timestamp;
    commission: number;
    reviewedAt: [] | [_Timestamp];
    orderId: bigint;
    amount: number;
    transactionId: string;
}): {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    sellerEarnings: number;
    userId: UserId;
    submittedAt: Timestamp;
    commission: number;
    reviewedAt?: Timestamp;
    orderId: bigint;
    amount: number;
    transactionId: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n23(_uploadFile, _downloadFile, value.status),
        method: from_candid_PaymentMethod_n25(_uploadFile, _downloadFile, value.method),
        sellerEarnings: value.sellerEarnings,
        userId: value.userId,
        submittedAt: value.submittedAt,
        commission: value.commission,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.reviewedAt)),
        orderId: value.orderId,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawStatus;
    method: _PaymentMethod;
    reviewedAt: [] | [_Timestamp];
    sellerId: _UserId;
    accountNumber: string;
    amount: number;
    requestedAt: _Timestamp;
}): {
    id: bigint;
    status: WithdrawStatus;
    method: PaymentMethod;
    reviewedAt?: Timestamp;
    sellerId: UserId;
    accountNumber: string;
    amount: number;
    requestedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawStatus_n35(_uploadFile, _downloadFile, value.status),
        method: from_candid_PaymentMethod_n25(_uploadFile, _downloadFile, value.method),
        reviewedAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.reviewedAt)),
        sellerId: value.sellerId,
        accountNumber: value.accountNumber,
        amount: value.amount,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    total: number;
    userId: _UserId;
    date: _Timestamp;
    items: Array<_OrderItem>;
}): {
    id: bigint;
    status: OrderStatus;
    total: number;
    userId: UserId;
    date: Timestamp;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n6(_uploadFile, _downloadFile, value.status),
        total: value.total,
        userId: value.userId,
        date: value.date,
        items: value.items
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Invalid: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): ReferralStatus {
    return "Invalid" in value ? ReferralStatus.Invalid : "Completed" in value ? ReferralStatus.Completed : "Pending" in value ? ReferralStatus.Pending : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Customer: null;
} | {
    Seller: null;
} | {
    Admin: null;
}): UserRole {
    return "Customer" in value ? UserRole.Customer : "Seller" in value ? UserRole.Seller : "Admin" in value ? UserRole.Admin : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): WithdrawStatus {
    return "Approved" in value ? WithdrawStatus.Approved : "Rejected" in value ? WithdrawStatus.Rejected : "Pending" in value ? WithdrawStatus.Pending : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Nagad: null;
} | {
    bKash: null;
}): PaymentMethod {
    return "Nagad" in value ? PaymentMethod.Nagad : "bKash" in value ? PaymentMethod.bKash : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Ongoing: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Ongoing" in value ? OrderStatus.Ongoing : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReferralRecord>): Array<ReferralRecord> {
    return value.map((x)=>from_candid_ReferralRecord_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawRequest>): Array<WithdrawRequest> {
    return value.map((x)=>from_candid_WithdrawRequest_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditEntry>): Array<AuditEntry> {
    return value.map((x)=>from_candid_AuditEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    Customer: null;
} | {
    Seller: null;
} | {
    Admin: null;
} {
    return value == UserRole.Customer ? {
        Customer: null
    } : value == UserRole.Seller ? {
        Seller: null
    } : value == UserRole.Admin ? {
        Admin: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    Nagad: null;
} | {
    bKash: null;
} {
    return value == PaymentMethod.Nagad ? {
        Nagad: null
    } : value == PaymentMethod.bKash ? {
        bKash: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Ongoing: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Ongoing ? {
        Ongoing: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
